apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
spec:
  selector:
    matchLabels:
      run: sampleapp
  replicas: 1
  template:
    metadata:
      labels:
        run: sampleapp
    spec:
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
      containers:
      - name: myapp
        image: alekhya277/sampleapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    run: sampleapp
  ports:
  - port: 80
    targetPort: 80

